package test.BasicUtils;
public class ObjectRepository 
{
	
	//Do not delete / edit 
	public static int valueCounterInteger = 430;
	
	//URLs and Logins :
	public static String ciscoLogin_Url = "https://sso-test.cisco.com/autho/forms/CECLogin.html";
	public static String mdmProxy_Url = "http://mdmui-wstg.cloudapps.cisco.com/mdmui/rest/proxyHome";
	public static String salesforce_url = "https://test.salesforce.com";
	public static String ccw_proxy_url = "https://pdricw-stage-b2x.cloudapps.cisco.com/ICW/PDR/proxyHome.do";
	public static String mdmProxyUsername = "meghgupt";
	public static String mdmProxyPassword = "Prisha#2017";
	public static String ccwProxyUsername = "sunchand";
	public static String ccwProxyPassword = "cisco123";
	public static String duabhish = "duabhish";
	
	//Default Estimate
	public static String estimateId = "GA73390439OV";	//GA73390439OV
		
	//Cisco Login Page
	public static String username_tb = "//input[@id='userInput']";
	public static String password_tb = "//input[@id='passwordInput']";
	public static String login_button = "//input[@id='login-button']";
	public static String proxyId_tb = "//input[@id='proxyId']";
	public static String proxyIdSubmit_button = "//button[@type='submit']";
	
	
	//Advanced Search Page
	public static String dealID_textbox = "//*[@kdfid='DealID' and @kdfapp='mdmUI' and @kdfpage='advancedSearch']";
	public static String advancedSearch_button = "//*[@kdfid='AdvSearchBtn' and @kdfapp='mdmUI' and @kdfpage='advancedSearch']";
	
	
	//My Deals Homepage
	public static String advancedSearch_link = "//*[@kdfid='advancedSearch' and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String dealID_link = "//*[starts-with(@kdfid,'deal-link-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	
	
	
	//SFDC Pages
	
	public static String sfdc_username_tb = "//input[@id='username']";
	public static String sfdc_password_tb = "//input[@id='password']";
	public static String sfdc_login_button = "//input[@id='Login']";
	public static String sfdc_changePasswordCancel_button = "//button[@id='cancel-button']";
	public static String createNew_tabdropdown = "//div[@id='createNew']/div";
	public static String sfdc_opportunity_link = "//div[@id='createNewMenu']/a[6]";
	//public static String sfdc_continue_button = "//td[@id='opptyNewOverride:theForm:theBlock:j_id14:bottom']/input";
	public static String sfdc_continue_button = "//td[contains(@id,'opptyNewOverride:theForm:theBlock')]/input";
	public static String sfdc_openSidebar_link = "//span[@id='pinIndicator']";
	public static String sfdc_createQuote_button = "//input[@name='new00N80000002zs9N']";
	
	
	public static String sfdc_moreActions_dropdown = "//*[@kdfid='tabInstallMoreAction kdfpage=' and @kdfapp='Quoting']";
	public static String sfdc_importSavedConfig_link = "//*[@kdfid='importSavedConfig' and @kdfapp='Quoting' and @kdfpage='itemstab']";
	public static String sfdc_savedconfigurationimport1_button = "//*[@kdfid='savedconfigurationimport1' and @kdfapp='Quoting' and @kdfpage='importsavedconfiguration']";
	public static String sfdc_txtEstimateSearchTxt_textbox = "//*[@kdfid='txtEstimateSearchTxt' and @kdfapp='buildnprice' and @kdfpage='importSavedConfigMenu']";
	public static String sfdc_btnSearchImportConfigMenu_button = "//*[@kdfid='btnSearchImportConfigMenu' and @kdfapp='buildnprice' and @kdfpage='importSavedConfigMenu']";
	public static String sfdc_estimateSearchResult_radio = "//*[starts-with(@kdfid,'rdRadCopyQuote_') and @kdfapp='buildnprice' and @kdfpage='importCopyQuoteTableData']/..";
	public static String sfdc_importEstimate_button = "//input[@id='importEstimateId2']";
	
	

	public static String value_8 = "//input[@name='save']";
	public static String value_6 = "//img[@id='00N30000000gPQx_right_arrow']";
	public static String value_7 = "//select[@id='00N30000002DhSk']";
	public static String inCiscoCapitalEngaged = "//select[@id='00N300000029y0B']";
	public static String theaterDropdown = "//select[@id='00N30000001c5cL']";
	public static String value_4 = "//select[@id='00N30000000gPQu']";
	public static String value_5 = "//*[@id='00N30000000gPQx_unselected']";
	public static String value_2 = "//*[@kdfid='dropdown-Active Deals - DEALS DESK' and @kdfapp='mdmUI' and @kdfpage='ngmdmPage']";
	public static String value_3 = "//select[@id='00N30000000gPQs']";
	//public static String value_1 = "http://mdmui-wstg.cloudapps.cisco.com/mdmui/rest/proxyHome";
	public static String value_15 = "//*[@kdfid='deleteBtn' and @kdfapp='mdmUI' and @kdfpage='deletepopup']";
	public static String value_26 = "//*[@kdfid='dealPricing' and @kdfapp='mdmUI' and @kdfpage='leftBar']/span";
	public static String value_16 = "//*[@kdfid='topDPSaveAndPublish' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_27 = "//*[@kdfid='fmvRevenue-Product' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_13 = "//*[@kdfid='expandAll' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_24 = "//div[@class='alert alert-danger']/span";
	public static String value_35 = "//*[@kdfid='cancelBtn' and @kdfapp='mdmUI' and @kdfpage='fvAssessment']";
	public static String value_14 = "//*[starts-with(@kdfid,'delete-') and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']/parent::div/parent::td/following-sibling::td[contains(text(),'PRODUCT')]/following-sibling::td[contains(text(),'Conditional Rebate')]/following-sibling::td[*]/span[contains(text(),'desc_03DPr_TC16')]/parent::td/preceding-sibling::td[last()]/div/a[starts-with(@kdfid,'delete-')]";
	public static String value_25 = "//*[@kdfid='DSslideMenu' and @kdfapp='mdmUI' and @kdfpage='ngDealSummary']";
	public static String value_19 = "//label[contains(text(),'Component')]/following-sibling::span/div/div/select";
	public static String value_17 = "//*[@kdfid='EditScenario' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_28 = "//*[@kdfid='fmvRevenue-TSS' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_18 = "//*[@kdfid='addAdjustmentLine' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_29 = "//*[@kdfid='fmvRevenue-Total' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_30 = "//*[@kdfid='utiFV' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_22 = "//*[@kdfid='adjustmentvalue' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_33 = "//td[contains(text(),'SERVICES')]/following-sibling::td[6]";
	public static String value_12 = "//*[starts-with(@kdfid,'compare-') and @kdfapp='mdmUI' and @kdfpage='ngScenarioBrowser']/parent::div/parent::td/following-sibling::td[*]/a[starts-with(@kdfid,'scenarioName-')]";
	public static String value_23 = "//*[@kdfid='AddNewBtn' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_34 = "//td[contains(text(),'Total')]/following-sibling::td[6]";
	public static String value_20 = "//label[contains(text(),'Line Type')]/following::select";
	public static String value_31 = "//*[@kdfid='fvAssessment' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_21 = "//*[@kdfid='description' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_32 = "//td[contains(text(),'PRODUCT')]/following-sibling::td[6]";
	
	public static String value_79 = "//*[@kdfid='icwSaveCiscoTradeinItem' and @kdfapp='Quoting' and @kdfpage='addTradeInItemstab']";
	
	public static String value_70 = "//*[@kdfid='icwButtonModalDone' and @kdfapp='config' and @kdfpage='xaasui']";
	public static String value_73 = "//*[@kdfid='addTradeInItems' and @kdfapp='Quoting' and @kdfpage='itemstab']";
	public static String value_74 = "//*[@kdfid='addCiscoTradeIn' and @kdfapp='Quoting' and @kdfpage='addTradeInItemstab']";
	public static String value_71 = "//div[@class='orderTitle quoteId']/div/h3";
	public static String value_72 = "//*[@kdfid='tabInstallMoreAction kdfpage=' and @kdfapp='Quoting']";
	public static String value_77 = "//div[@class='ac_results']/ul/li/div/strong";
	public static String value_78 = "//*[@kdfid='ciscoQuantity' and @kdfapp='Quoting' and @kdfpage='addTradeInItemstab']";
	public static String value_75 = "//*[@kdfid='ciscoPartNumber' and @kdfapp='Quoting' and @kdfpage='addTradeInItemstab']";
	public static String value_76 = "//*[@kdfid='ciscoProductFamily' and @kdfapp='Quoting' and @kdfpage='addTradeInItemstab']";
	public static String value_68 = "//*[contains(text(),'Configuration Summary')]";
	public static String value_110 = "//label[contains(text(),'Approval Route')]";
	public static String value_69 = "//*[@kdfid='doneConfig' and @kdfapp='config' and @kdfpage='xaasui']";
	public static String sfdc_skuQty_tb = "//*[@kdfid='searchQty' and @kdfapp='Quoting' and @kdfpage='itemstab']";
	public static String sfdc_addSku_button = "//*[@kdfid='AddSKU' and @kdfapp='Quoting' and @kdfpage='itemstab']";
	public static String service_duration_tb = "//*[@kdfid='serviceDuration' and @kdfapp='Quoting' and @kdfpage='addServiceItemPage']";
	public static String service_add_button = "//*[@kdfid='AddServiceSKUButton' and @kdfapp='Quoting' and @kdfpage='addServiceItemPage']";
	public static String value_60 = "//*[@kdfid='createDealBtn' and @kdfapp='Quoting'  and @value='Create Quote']";
	public static String sfdc_createQuote_label = "//*[contains(text(),'Create Quote')]";
	public static String sfdc_descriptionProduct_tb = "//*[@kdfid='descriptionProduct' and @kdfapp='Quoting' and @kdfpage='itemstab']";
	public static String value_66 = "//*[@kdfid='rdo_NU_STD_MTG' and @kdfapp='config' and @kdfpage='xaasui']/..";
	//public static String value_67 = "//*[@kdfid='quantityInput_A-WX-NU-MTGS-25' and @kdfapp='config' and @kdfpage='xaasui']";
	public static String value_67 = "//*[starts-with(@kdfid,'quantityInput_') and @kdfapp='config' and @kdfpage='xaasui']";
	public static String value_64 = "//*[@kdfid='tabDynaSelectoptions' and @kdfapp='Quoting' and @kdfpage='itemstab']/span";
	//public static String value_65 = "//*[@kdfid='linkIndent_WEBEX-SAAS-MODEL:CONF_G' and @kdfapp='config' and @kdfpage='xaasui']";
	public static String value_65 = "//*[starts-with(@kdfid,'linkIndent_') and @kdfapp='config' and @kdfpage='xaasui']";
	public static String value_59 = "//*[@kdfid='dealCategory_2' and @kdfapp='Quoting']";
	public static String value_57 = "//*[@kdfid='sourceProfileId_1' and @kdfapp='Quoting']";
	public static String value_58 = "//*[@kdfid='dealCategory' and @kdfapp='Quoting']";
	public static String value_100 = "//*[@kdfid='textarea_2085864384' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_101 = "//*[@kdfid='qualformselect_147' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_102 = "//*[@kdfid='qualformselect_147_2509374741' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_103 = "//*[@kdfid='qualformaddcompetitor' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_104 = "//*[@kdfid='addcompetitormodalcontinue' and @kdfapp='Quoting' and @kdfpage='qualformaddcompetitormodal']";
	public static String value_105 = "//*[@kdfid='qualformselect_2085864217' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_106 = "//*[@kdfid='qualformselect_2085864217_2561827' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_107 = "//*[@kdfid='qualformsaveandcontinue' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_108 = "//*[@kdfid='submitCheck' and @kdfapp='Quoting' and @kdfpage='nsReviewSubmit']/..";
	public static String yesRadioButton_submitPage = "//*[@kdfid='atOrBelowRadio' and @kdfapp='Quoting' and @kdfpage='nsReviewSubmit']";
	public static String value_109 = "//*[@kdfid='subDealforQualification' and @kdfapp='Quoting' and @kdfpage='nsReviewSubmit']";
	public static String value_91 = "//input[@value='Continue']";
	public static String value_92 = "//h5[contains(text(),'Deal ID')]/following-sibling::div/h3";
	public static String value_90 = "//*[@kdfid='viewquotequalifysubmit' and @kdfapp='Quoting' and @kdfpage='quoteOverviewPage']";
	public static String value_51 = "//div[@id='myModal2']/div[2]/div/div[3]/button";
	public static String value_95 = "//*[@kdfid='qualformselect_176_47939940' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_52 = "mixPercentageIdValue_0";
	public static String value_96 = "//*[@kdfid='textarea_2085864344' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_93 = "//*[@kdfid='textinput_47939941' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_50 = "//a[@id='techNameToExpand']";
	public static String value_94 = "//*[@kdfid='qualformselect_176' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_55 = "//*[@kdfid='rnsdConfirmation_n' and @kdfapp='Quoting' ]/..";
	public static String value_99 = "//*[@kdfid='textarea_2085864421' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_56 = "//*[@kdfid='sourceProfileId' and @kdfapp='Quoting']";
	public static String value_53 = "//button[@id='saveTech']";
	public static String value_97 = "//*[@kdfid='qualformselect_8' and @kdfapp='Quoting' and @kdfpage='qualform']";
	
	public static String value_98 = "//*[@kdfid='qualformselect_8_54' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_48 = "//div[@id='j_id0:j_id17:j_id19:j_id23:j_id32:j_id34']/select";
	public static String value_49 = "//div[@id='technologyApplication']/div/span/button";
	public static String value_46 = "//input[@id='00N30000000gPQn']";
	public static String value_47 = "//select[@id='opp11']";
	public static String value_80 = "//*[@kdfid='icwButtonSaveandContinue' and @kdfapp='Quoting' and @kdfpage='addTradeInItemstab']";
	public static String value_81 = "//*[@kdfid='nonstandardFADisct' and @kdfapp='Quoting' and @kdfpage='discountscreditstab']";
	
	public static String value_84 = "//*[@kdfid='btnCalculate' and @kdfapp='Quoting' and @kdfpage='discountSummaryModal']";
	
	public static String value_85 = "//*[@kdfid='btnSave' and @kdfapp='Quoting' and @kdfpage='discountSummaryModal']";
	public static String productDiscount_tb = "//*[@kdfid='productTotDisct' and @kdfapp='Quoting' and @kdfpage='DiscCredits']";
	public static String serviceDiscount_tb = "//*[@kdfid='serviceTotDisct' and @kdfapp='Quoting' and @kdfpage='DiscCredits']";
	public static String subscriptionDiscount_tb = "//*[@kdfid='subsTotDisct' and @kdfapp='Quoting' and @kdfpage='DiscCredits']";
	
	public static String value_44 = "//input[@id='opp3']";
	public static String value_88 = "//input[@id='icwModal_confirmCreditAdjustment']";
	
	//Non-rewrite Quote Initiation Page
	public static String transactional_radio = "//*[@kdfid='rnsdConfirmation_n' and @kdfapp='Quoting' and @kdfpage='']/..";
	public static String rnsd_radio = "//*[@kdfid='rnsdConfirmation_y' and @kdfapp='Quoting' and @kdfpage='']/..";
	public static String proceList_dropdown = "//*[@kdfid='erpPriceListId' and @kdfapp='Quoting']";
	public static String priceList_USD_value = "//*[@kdfid='erpPriceListId_1108' and @kdfapp='Quoting']";
	public static String buyMethod_dropdown = "//*[@kdfid='sourceProfileId' and @kdfapp='Quoting']";
	public static String buyMethod_Cisco_value = "//*[@kdfid='sourceProfileId_1' and @kdfapp='Quoting']";
	public static String dealCategory_dropdown = "//*[@kdfid='dealCategory' and @kdfapp='Quoting']";
	public static String dealCategory_Outsource_value = "//*[@kdfid='dealCategory_2' and @kdfapp='Quoting']";
	public static String createDeal_button = "//*[@kdfid='createDealBtn' and @kdfapp='Quoting']";
	
	
	public static String value_89 = "//*[@kdfid='submitandreview' and @kdfapp='Quoting' and @kdfpage='reviewandsubmit']";
	
	public static String saveAndCont_dnc_button = "//*[@kdfid='pdrButtonSaveandContinue' and @kdfapp='Quoting' and @kdfpage='discountscreditstab']";
	public static String value_43 = "//input[@id='opp4']";
	public static String value_45 = "//span/span/a";
	public static String accName_autoPopulated = "//strong[@class='autocompleteMatch']";
	public static String value_87 = "//*[@kdfid='adjustTradeInDiscount' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String sfdc_setQuotePreferences_link = "//a[contains(text(), 'Set preferences for this quote')]";
	public static String sfdc_selfService_radio = "//*[@kdfid='selfService' and @kdfapp='Quoting' and @kdfpage='itemstab']/..";
	public static String value_122 = "//div[@id='preferences']/div/a";
	public static String saveAndCont_itemsTab_button = "//*[@kdfid='tabIcwButtonSaveandContinue' and @kdfapp='Quoting' and @kdfpage='itemstab']";
	public static String value_124 = "//div[@id='reviewPageErrors']/descendant::span[contains(text(),'This Quote contains serviceable items without any services attached')]";
	public static String value_125 = "//div[@class='select-reason-field']/descendant::a[@title='Select']";
	public static String value_126 = "//*[@kdfid='_RC_001' and @kdfapp='Quoting']";
	public static String value_127 = "//*[@kdfid='textarea_47939905' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_128 = "//*[@kdfid='qualformselect_123' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_129 = "//*[@kdfid='qualformselect_123_175534971' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_130 = "1";
	public static String value_131 = "//span[@class='icwOrderName' and text()!='']";
	public static String value_132 = "//div[contains(@class,'icwHeaderInfo')]/strong[1][text()!='']";
	public static String value_111 = "//span[@class='zen-assistiveText' and contains(text(),'Click to Open Sidebar')]";
	public static String value_133 = "//div[contains(@class,'icwHeaderInfo')]/strong[2][text()!='']";
	public static String value_112 = "//label[contains(text(),'Forecasting Position')]/../following-sibling::td/descendant::select";
	public static String value_134 = "//div[contains(@class,'icwHeaderInfo')]/strong[3][text()!='']";
	public static String value_113 = "//span[@class='cartlink']/button";
	public static String value_135 = "//div[@class='tabContent']/div[2][@class='rightData' and text()!='']";
	public static String value_114 = "//button[@data-dismiss='modal' and text()='Close']";
	public static String value_136 = "//div[@class='tabContent']/div[4][@class='rightData' and text()!='']";
	public static String value_115 = "//*[@kdfid='rnsdConfirmation_n' and @kdfapp='Quoting' and @kdfpage='CreateQuote']/following-sibling::label";
	public static String value_137 = "//div[@id='approversListWrapper']";
	public static String value_116 = "//*[@kdfid='erpPriceListId' and @kdfapp='Quoting' and @kdfpage='CreateQuote']";
	public static String value_138 = "//*[@kdfid='viewSubmittedQuote' and @kdfapp='Quoting' and @kdfpage='confirmationPage']";
	public static String value_117 = "//*[@kdfid='sourceProfileId' and @kdfapp='Quoting' and @kdfpage='CreateQuote']";
	public static String value_118 = "//*[@kdfid='dealCategory' and @kdfapp='Quoting' and @kdfpage='CreateQuote']";
	public static String value_119 = "//*[@kdfid='createQuote' and @kdfapp='Quoting' and @kdfpage='CreateQuote']";
	public static String value_139 = "3";
	public static String value_141 = "//*[@kdfid='expandAll' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_163 = "//*[@kdfid='textinput_47939941' and @kdfapp='Quoting' and @kdfpage='qualform' and @value='4']";
	public static String value_185 = "23";
	public static String value_142 = "//*[@kdfid='text47939941' and @kdfapp='mdmUI' and @kdfpage='ngQualification']/div/input";
	public static String value_164 = "//td[contains(text(),'ADC')]";
	public static String value_186 = "25";
	public static String value_143 = "//*[@kdfid='multiSelect11519171098' and @kdfapp='mdmUI' and @kdfpage='ngQualification']/div/button";
	public static String value_165 = "//td[contains(text(),'COLLABORATION-Conferencing')]";
	public static String value_187 = "27";
	public static String value_144 = "//label[contains(text(),'UCS Mini')]";
	public static String value_166 = "//td[contains(text(),'testAddCompetetor')]";
	public static String value_145 = "//*[@kdfid='select8' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_167 = "//div[@id='summaryFor-11519171098']";
	public static String value_146 = "//*[@kdfid='select123' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_168 = "//div[@id='summaryFor-8']";
	public static String value_147 = "//*[@kdfid='Area Manager' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_169 = "//div[@id='summaryFor-123']";
	public static String value_148 = "//*[@kdfid='Area Director' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_149 = "//*[@kdfid='Sales System Engineer' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_170 = "5";
	public static String value_171 = "7";
	public static String value_150 = "//*[@kdfid='competitoroption' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_172 = "9";
	public static String value_151 = "//*[@kdfid='competitortechoption' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_173 = "11";
	public static String value_152 = "//*[@kdfid='comments36' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_174 = "12";
	public static String value_153 = "//*[@kdfid='addCompBtn' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_175 = "//select[@id='00N80000002kpzu_unselected']";
	public static String value_154 = "//*[@kdfid='saveandpublicontinue' and @kdfapp='mdmUI' and @kdfpage='ngQualification']";
	public static String value_176 = "//img[@id='00N80000002kpzu_right_arrow']";
	public static String value_155 = "//input[@id='phSearchInput']";
	public static String value_177 = "//*[@kdfid='qualformselect_31' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_156 = "//input[@id='phSearchButton']";
	public static String value_178 = "//*[@kdfid='qualformselect_31_148' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_157 = "//table[@class='list']/tbody/tr[2]/th/a";
	public static String value_179 = "//*[@kdfid='qualformselect_30' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_158 = "//input[@name='quote_overview']";
	public static String value_159 = "//a[@kdfid='qualifySubmitLink' and @kdfpage='quoteOverviewPage' and @kdfapp='Quoting']/b";
	public static String value_180 = "//*[@kdfid='qualformselect_30_146' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_181 = "//*[@kdfid='qualformselect_29' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_160 = "//*[@kdfid='lookuptext_172' and @kdfapp='Quoting' and @kdfpage='qualform' and contains(@value,'JOHN HURLEY')]";
	public static String value_182 = "//*[@kdfid='qualformselect_29_144' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_161 = "//*[@kdfid='lookuptext_173' and @kdfapp='Quoting' and @kdfpage='qualform' and contains(@value,'JOHN HURLEY')]";
	public static String value_183 = "19";
	public static String value_140 = "//*[@kdfid='qualification' and @kdfapp='mdmUI' and @kdfpage='leftBar']/span";
	public static String value_162 = "//*[@kdfid='lookuptext_171' and @kdfapp='Quoting' and @kdfpage='qualform' and contains(@value,'JOHN HURLEY')]";
	public static String value_184 = "21";
	public static String value_196 = "//*[@kdfid='_RC_002' and @kdfapp='Quoting']";
	public static String value_188 = "//td[@id='opptyNewOverride:theForm:theBlock:j_id10:bottom']/input";
	public static String value_189 = "//*[@kdfid='rnsdConfirmation' and @kdfpage='CreateQuote' and @kdfapp='Quoting' ]/following-sibling::label";
	public static String value_190 = "//*[@kdfid='subsTotDisct' and @kdfapp='Quoting' and @kdfpage='DiscCredits']";
	public static String value_191 = "//b[contains(text(),'Is this a Multi-Element Arrangement (MEA) Deal?')]";
	public static String value_192 = "//*[@kdfid='qualformselect_176_47939939' and @kdfapp='Quoting' and @kdfpage='qualform']";
	public static String value_193 = "//b[contains(text(),'What is the reason for request?')]";
	public static String value_194 = "//*[@kdfid='atOrBelowRadio' and @kdfapp='Quoting' and @kdfpage='nsReviewSubmit']";
	public static String value_195 = "//div[@class='select-reason-field']/descendant::a[starts-with(@id,'sbSelector')]";
	public static String value_197 = "//*[@kdfid='linkIndent_HCS-ONPREM-MODEL:HCS_UCM2_G' and @kdfapp='config' and @kdfpage='xaasui']";
	public static String value_198 = "//*[@kdfid='quantityInput_A-HCS-UC-FND-K9' and @kdfapp='config' and @kdfpage='xaasui']";
	public static String value_199 = "//span[contains(text(),'Configuration Summary')]";
	public static String value_200 = "//input[@id='addSpecialItem']";
	public static String value_201 = "//*[@kdfid='productFamily' and @kdfapp='Quoting' and @kdfpage='addSpecialItemsModal']";
	public static String value_202 = "//div[@class='ac_results'][*]/ul/li/div";
	public static String value_203 = "//*[@kdfid='partNumber' and @kdfapp='Quoting' and @kdfpage='addSpecialItemsModal']";
	public static String value_204 = "//*[@kdfid='description' and @kdfapp='Quoting' and @kdfpage='addSpecialItemsModal']";
	public static String value_205 = "//*[@kdfid='listPrice' and @kdfapp='Quoting' and @kdfpage='addSpecialItemsModal']";
	public static String value_206 = "//*[@kdfid='quantity' and @kdfapp='Quoting' and @kdfpage='addSpecialItemsModal']";
	public static String value_207 = "//*[@kdfid='btnSaveData' and @kdfapp='Quoting' and @kdfpage='addSpecialItemsModal']";
	public static String value_240 = "//*[@kdfid='buttonReopenDeal' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_241 = "//*[@kdfid='forecastingPositionEdit' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_220 = "//*[@kdfid='partnerAddressNav' and @kdfapp='Quoting' and @kdfpage='createQuote']";
	public static String value_242 = "//*[@kdfid='forecastingPositions_xxx' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_221 = "//*[@kdfid='selectedContactFlag' and @kdfapp='Quoting' and @kdfpage='createQuote']/following-sibling::label";
	public static String value_243 = "//*[@kdfid='forecastingPositionUpdate' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String salesHierarchy_rns = "//div[contains(@class,'dealSearchPortlet') and contains(@data-bind,'salesGeography') and text()!=' ']";
	//public static String salesHierarchy_rns_null = "//div[contains(@class,'dealSearchPortlet') and contains(@data-bind,'salesGeography') and text()=' ']";
	public static String value_222 = "//*[@kdfid='createDealBtn' and @kdfapp='Quoting' and @kdfpage='createQuote']";
	public static String value_223 = "//*[@kdfid='dealDescription' and @kdfapp='Quoting' and @kdfpage='aboutTheDeal']";
	public static String dealCategoryDropdown = "//*[@kdfid='dealCategory' and @kdfapp='Quoting' and @kdfpage='aboutTheDeal']";
	public static String intendedUseDropdown = "//*[@kdfid='intendedUse' and @kdfapp='Quoting' and @kdfpage='aboutTheDeal']";
	public static String priceListDropdown = "//*[@kdfid='erpPriceListId' and @kdfapp='Quoting' and @kdfpage='aboutTheDeal']";
	public static String calenderIcon = "//*[@kdfid='calendarIcon' and @kdfapp='Quoting' and @kdfpage='aboutTheDeal']";
	public static String calenderNextMonth = "//button[contains(@class,'pull-right')]";
	public static String calenderNextMonthDate = "//table[@class='uib-daypicker']/tbody/tr[2]/td/button";
	public static String buyMethod_CCW_dropdown = "//*[@kdfid='fulfillmentSelect' and @kdfapp='Quoting' and @kdfpage='initialQuote']";
	public static String buyMethod_cisco_CCW_dropdownvalue = "//*[@kdfid='fulfillmentSelect_1-Tier' and @kdfapp='Quoting' and @kdfpage='initialQuote']";
	
	public static String value_209 = "//*[@kdfid='idproxyUserId' and @kdfapp='Quoting' and @kdfpage='proxyhome']";
	public static String saveAndContinueFromAboutTheDealPage = "//*[@kdfid='saveAndContinueGDRAction' and @kdfapp='Quoting' and @kdfpage='aboutTheDeal']";
	public static String value_231 = "//*[@kdfid='buyMethod' and @kdfapp='quote' and @kdfpage='quote']";
	public static String value_210 = "//*[@kdfid='loginToCCW' and @kdfapp='Quoting' and @kdfpage='proxyhome']";
	public static String value_232 = "//*[@kdfid='continueBtn' and @kdfapp='quote' and @kdfpage='quote']";
	public static String saveAndContinueFromQIP = "//*[@kdfid='icwButtonSaveandContinue' and @kdfapp='Quoting' and @kdfpage='quoteItems']";
	public static String value_211 = "//*[@kdfid='createquotebtn' and @kdfapp='Quoting' and @kdfpage='ccwdashboard']";
	public static String value_233 = "//dd[contains(@data-ng-if,'dealHeader.globalDeal') or contains(@data-ng-if,'dealHeader.localDeal')]";
	public static String dealId_nonrw_ccw_text = "//div[@class='orderTitle quoteId']/descendant::h3";
	public static String value_212 = "//*[@kdfid='dealName' and @kdfapp='Quoting' and @kdfpage='createQuote']";
	public static String value_234 = "//*[@kdfid='whoIsInvolvedLnk' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_213 = "//*[@kdfid='selectedCAMId' and @kdfapp='Quoting' and @kdfpage='createQuote']";
	public static String value_235 = "//*[@kdfid='advancedSearch' and @kdfapp='Quoting' and @kdfpage='ccwdashboard']";
	public static String value_214 = "//*[@kdfid='selectedCAMIdOther' and @kdfapp='Quoting' and @kdfpage='createQuote']";
	public static String value_236 = "//*[@kdfid='dealViewAdv' and @kdfapp='Quoting' and @kdfpage='ccwdashboard']";
	public static String value_215 = "//*[@kdfid='endCustomerFasterSearch' and @kdfapp='Quoting' and @kdfpage='createQuote']";
	public static String value_237 = "//*[@kdfid='dealId' and @kdfapp='Quoting' and @kdfpage='ccwdashboard']";
	public static String value_216 = "//*[@kdfid='addEC' and @kdfapp='Quoting' and @kdfpage='fasterSearch']";
	public static String value_238 = "//*[@kdfid='advSearch' and @kdfapp='Quoting' and @kdfpage='ccwdashboard']";
	public static String value_217 = "//*[@kdfid='searchButton' and @kdfapp='Quoting' and @kdfpage='fasterSearch']";
	public static String value_239 = "//*[@kdfid='dealId_0' and @kdfapp='Quoting' and @kdfpage='ccwdashboard']";
	public static String value_218 = "//input[starts-with(@kdfid,'recentCustomer_')]/ancestor::tbody/tr[*]/descendant::td[text()='UNITED STATES']/parent::tr/descendant::input[starts-with(@kdfid,'recentCustomer_')]/following-sibling::label";
	public static String value_219 = "//*[@kdfid='selectValueButton' and @kdfapp='Quoting' and @kdfpage='fasterSearch']";
	public static String value_244 = "//span[contains(@class,'createdByfilter')]/descendant::a";
	public static String value_245 = "//*[@kdfid='optEstimatehierarchyLevel2ALL' and @kdfapp='buildnprice' and @kdfpage='importSavedConfigMenu']";
	public static String value_246 = "//input[starts-with(@kdfid,'rdRadCopyQuote') and @kdfapp='buildnprice' and @kdfpage='importCopyQuoteTableData']/parent::label";
	public static String value_247 = "//*[@kdfid='btnImportEstimateICT' and @kdfapp='buildnprice' and @kdfpage='importSavedConfigMenu' and @value='Import Entire Estimate']";
	public static String value_251 = "//*[@kdfid='reasonCode' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_252 = "//*[@kdfid='reasonCode_5' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_253 = "//*[@kdfid='selectAM' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_248 = "//*[@kdfid='differentAM' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String notNullAmValue_rnsPage = "//div[@class='icwAmSection']/descendant::span[@data-bind='text:name' and text()!='']";
	public static String value_249 = "//*[@kdfid='amEmailId' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']";
	public static String value_250 = "//*[@kdfid='amEmailId' and @kdfapp='Quoting' and @kdfpage='reviewAndSubmit']/following::a[@kdfid='amEmailId_' and contains(text(),'thaymore')]";
	public static String value_262 = "//*[starts-with(@kdfid,'assurerName-') and @kdfapp='mdmUI' and @kdfpage='ngDealSummary' and contains(translate(text(),'NGAZALEH','ngazaleh'),'ngazaleh')]";
	public static String value_263 = "//td[starts-with(@kdfid,'assurerName-') and @kdfapp='mdmUI' and @kdfpage='ngDealSummary' and contains(translate(text(),'NGAZALEH','ngazaleh'),'ngazaleh')]/preceding-sibling::td[*]/span/input";
	public static String value_264 = "//*[@kdfid='sendRequestAssurer' and @kdfapp='mdmUI' and @kdfpage='ngDealsummary']";
	public static String value_254 = "https://mdmui-wstg.cloudapps.cisco.com/mdmui/rest/proxyHome";
	public static String value_265 = "//td[starts-with(@kdfid,'assurerName-') and @kdfapp='mdmUI' and @kdfpage='ngDealSummary' and contains(translate(text(),'NGAZALEH','ngazaleh'),'ngazaleh')]/preceding-sibling::td[starts-with(@kdfid,'assuranceStatus-')]";
	public static String value_255 = "//*[@kdfid='dealSummary' and @kdfapp='mdmUI' and @kdfpage='leftBar']/span";
	public static String value_266 = "//td[starts-with(@kdfid,'assurerName-') and @kdfapp='mdmUI' and @kdfpage='ngDealSummary' and contains(translate(text(),'NGAZALEH','ngazaleh'),'ngazaleh')]/parent::tr/parent::tbody/tr[last()]/td[2]/div/a[2]";
	public static String value_256 = "//*[@kdfid='DSExpandAll' and @kdfapp='mdmUI' and @kdfpage='ngDealSummary']";
	public static String value_267 = "//label[contains(text(),'Decision')]/following-sibling::div/select";
	public static String value_257 = "//*[@kdfid='addAssurer' and @kdfapp='mdmUI' and @kdfpage='ngDealSummary']";
	public static String value_268 = "//*[@kdfid='comments' and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_258 = "//label[contains(text(),'Non Standard ')]/following-sibling::div/select";
	public static String value_269 = "//*[@kdfid='saveBtn' and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_259 = "//div[4]/input[starts-with(@typeahead,'user') and @placeholder='Name/CEC ID']";
	public static String value_270 = "//*[@kdfid='dealHeaderDealStatus' and @kdfapp='mdmUI' and @kdfpage='DealHeader']";
	public static String value_260 = "//*[@kdfid='assInstructions' and @kdfapp='mdmUI' and @kdfpage='addassurer']";
	public static String value_261 = "//*[@kdfid='assurSaveBtn' and @kdfapp='mdmUI' and @kdfpage='addassurer']";
	public static String value_284 = "//*[@kdfid='preFmvNetPrice-Total' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_285 = "//*[@kdfid='preFmvDiscount-Product' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_286 = "//*[@kdfid='preFmvDiscount-TSS' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_287 = "//*[@kdfid='preFmvDiscount-Total' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_320 = "//*[starts-with(@kdfid,'dealType-') and @kdfapp='mdmUI' and @kdfpage='myDeals']/ancestor::tbody/tr[last()]/descendant::span[starts-with(@kdfid,'dealType-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_288 = "//*[@kdfid='preFmvMargin-Product' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_321 = "//span[@id='tablePagination_totalPages' and text()>10]/preceding-sibling::span[1]";
	public static String value_289 = "//*[@kdfid='preFmvMargin-TSS' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_322 = "//*[starts-with(@kdfid,'myDealGrid-Next') and @kdfapp='mdmUI' and starts-with(@kdfpage,'myDealPage-Next')]";
	public static String value_323 = "//*[starts-with(@kdfid,'myDealGrid-First') and starts-with(@kdfpage,'myDealPage-First')]";
	public static String value_324 = "//*[starts-with(@kdfid,'myDealGrid-Prev') and @kdfapp='mdmUI' and starts-with(@kdfpage,'myDealPage-Prev')]";
	public static String value_325 = "//*[starts-with(@kdfid,'myDealGrid-Last') and @kdfapp='mdmUI' and starts-with(@kdfpage,'myDealPage-Last')]";
	public static String value_326 = "//div[@id='tablePagination']/descendant::select[starts-with(@kdfid,'dropdown-') and @kdfapp='mdmUI' and @kdfpage='ngmdmPage']";
	public static String value_327 = "//table[contains(@class,'table')]/descendant::tbody[count(tr)=15]";
	public static String value_328 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Deal Status']";
	public static String value_329 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Opportunity Name']";
	public static String value_290 = "//*[@kdfid='preFmvMargin-Total' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_291 = "//*[@kdfid='Deals' and @kdfapp='mdmUI' and @kdfpage='leftBar']/span";
	public static String value_292 = "//*[starts-with(@kdfid,'icon-preview-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_293 = "//h3[@class='modal-title']";
	public static String value_294 = "//*[@kdfid='exesummaryProductDD' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_273 = "//*[starts-with(@kdfid,'productDD-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_350 = "//span[@class='sub-menu-arrow']/parent::div/parent::I";
	public static String value_274 = "//*[starts-with(@kdfid,'serviceDD-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_351 = "//*[@kdfid='changeAccess' and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_275 = "//*[starts-with(@kdfid,'country-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_352 = "//td[contains(text(),'PAUCLARK')]/preceding-sibling::td/input[contains(@kdfid,'PAUCLARK')]";
	public static String value_276 = "//*[starts-with(@kdfid,'optyName-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_353 = "//*[@kdfid='savebtn' and @kdfapp='mdmUI' and @kdfpage='changeAccess']";
	public static String value_277 = "//*[starts-with(@kdfid,'optyOwner-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_310 = "//*[@kdfid='exesummaryGrossMargin-Total' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_354 = "//*[starts-with(@kdfid,'editicon-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_278 = "//*[starts-with(@kdfid,'accName-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_311 = "//*[@kdfid='exesummaryDealId' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_355 = "//*[@kdfid='editDealServiceDD' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_279 = "//*[starts-with(@kdfid,'recentSubmission-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_312 = "//*[@kdfid='dealStatus' and @kdfapp='mdmUI' and @kdfpage='advancedSearch']/select";
	public static String value_356 = "//*[@kdfid='editDealProductDD' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_313 = "//*[@kdfid='exesummaryDealId' and @kdfapp='mdmUI' and @kdfpage='executiveSummary' and string-length(text())=8]";
	public static String value_357 = "//*[@kdfid='editDealSave' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_314 = "//*[@kdfid='dealType' and @kdfapp='mdmUI' and @kdfpage='advancedSearch']/select";
	public static String value_358 = "//img[contains(@src,'preloader')]";
	public static String value_315 = "//*[@kdfid='execsummaryExport' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_316 = "//*[@kdfid='exesummaryClose' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_317 = "//*[starts-with(@kdfid,'dealStatus-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_318 = "//*[@kdfid='dropdown-Approved' and @kdfapp='mdmUI' and @kdfpage='ngmdmPage']";
	public static String value_319 = "//*[starts-with(@kdfid,'dealType-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_280 = "//*[starts-with(@kdfid,'dealNetPrice-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_281 = "//*[@kdfid='ScenarioBrowser' and @kdfapp='mdmUI' and @kdfpage='leftBar']/span";
	public static String value_282 = "//*[@kdfid='preFmvNetPrice-Product' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_283 = "//*[@kdfid='preFmvNetPrice-TSS' and @kdfapp='mdmUI' and @kdfpage='ngDealPricing']";
	public static String value_340 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Account Name']";
	public static String value_341 = "//*[starts-with(@kdfid,'accName') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_342 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Recent Submit Date']";
	public static String value_343 = "//*[starts-with(@kdfid,'recentSubmission') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_300 = "//*[@kdfid='exesummaryAccName' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_344 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Multiple Quotes']";
	public static String value_301 = "//*[@kdfid='exesummaryNetPrice-Product' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_345 = "//*[starts-with(@kdfid,'multiQuote') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_302 = "//*[@kdfid='exesummaryNetPrice-TSS-Core' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']/preceding-sibling::td/strong";
	public static String value_346 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Level2']";
	public static String value_303 = "//*[@kdfid='exesummaryNetPrice-TSS-Core' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_347 = "//*[starts-with(@kdfid,'area') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_304 = "//*[@kdfid='exesummaryNetPrice-Total' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_348 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Country']";
	public static String value_305 = "//*[@kdfid='exesummaryEffDisc-Product' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_349 = "//*[starts-with(@kdfid,'country') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_306 = "//*[@kdfid='exesummaryEffDisc-TSS-Core' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_307 = "//*[@kdfid='exesummaryEffDisc-Total' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_308 = "//*[@kdfid='exesummaryGrossMargin-Product' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_309 = "//*[@kdfid='exesummaryGrossMargin-TSS-Core' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_271 = "//*[@kdfid='dropdown-Approval Required' and @kdfapp='mdmUI' and @kdfpage='ngmdmPage']";
	public static String value_272 = "//*[@kdfid='dropdown-Assurance Required' and @kdfapp='mdmUI' and @kdfpage='ngmdmPage']";
	public static String value_295 = "//*[@kdfid='exesummaryServiceDD' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_296 = "//*[@kdfid='exesummaryCountry' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_297 = "//*[@kdfid='exesummaryOptName' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_330 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Deal Type']";
	public static String value_298 = "//*[@kdfid='exesummaryOptOwner' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_331 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Ext. List Price']";
	public static String value_299 = "//*[@kdfid='exesummaryPriceList' and @kdfapp='mdmUI' and @kdfpage='executiveSummary' and text()!='']";
	public static String value_332 = "//*[starts-with(@kdfid,'dealListPrice-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_333 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Ext. Net Price']";
	public static String value_334 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Service DD']";
	public static String value_335 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Primary Product DD']";
	public static String value_336 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Opportunity Owner']";
	public static String value_337 = "//*[starts-with(@kdfid,'optyOwner') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_338 = "//table[contains(@class,'table')]/descendant::thead/tr[1]/descendant::a[text()='Expiration Date']";
	public static String value_339 = "//*[starts-with(@kdfid,'expireDate') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_361 = "//*[@kdfid='defaultDecision' and @kdfapp='mdmUI' and @kdfpage='updateApprovalDecision']";
	public static String value_362 = "//*[@kdfid='cancelBtn' and @kdfapp='mdmUI' and @kdfpage='updateApprovalDecision']";
	public static String value_363 = "//*[@kdfid='exesummaryPriceList' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_364 = "//*[@kdfid='exesummaryPartner' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_365 = "//*[@kdfid='exesummaryExpectedBookDate' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_366 = "//*[@kdfid='exesummaryForCastStatus' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_367 = "//*[@kdfid='exesummaryforcastQuater' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_400 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()!=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_368 = "//*[@kdfid='editDealLabel' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_401 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/preceding-sibling::td[starts-with(@kdfid,'theater_')]";
	public static String value_369 = "//label[contains(text(),'Deal Status')]/following::select[starts-with(@kdfid,'dropdown-')]";
	public static String value_402 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_403 = "//table[contains(@aria-activedescendant,'datepicker')]/tbody/tr[2]/td[2]/button/span";
	public static String value_404 = "//*[@kdfid='displayUserName' and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_405 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER') and @kdfapp='mdmUI' and @kdfpage='existingProxy']/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()!=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/following-sibling::td/a[starts-with(@kdfid,'editicon')]";
	public static String value_406 = "//*[starts-with(@kdfid,'theater_') and @kdfapp='mdmUI' and @kdfpage='existingProxy' and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/preceding-sibling::td[contains(@kdfid,'proxyGivenBy')]";
	public static String value_407 = "//*[starts-with(@kdfid,'theater_') and @kdfapp='mdmUI' and @kdfpage='existingProxy' and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]";
	public static String value_408 = "//td[starts-with(@kdfid,'userJobRole_') and @kdfapp='mdmUI' and @kdfpage='existingProxy' and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]";
	public static String value_409 = "//*[starts-with(@kdfid,'theater_') and @kdfapp='mdmUI' and @kdfpage='existingProxy' and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_370 = "//*[@kdfid='editDealDealId' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_371 = "//*[@kdfid='editDealAppReq' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_394 = "//div[@ng-switch='datepickerMode']/descendant::button[not(@disabled='disabled') and contains(@class,'btn btn-default')]/span";
	public static String value_395 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate_')]";
	public static String value_396 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]/following-sibling::td[starts-with(@kdfid,'proxyEndDate_')]";
	public static String value_397 = "//*[@kdfid='pdq' and @kdfapp='mdmUI' and @kdfpage='myDeals']/select";
	public static String value_398 = "//*[starts-with(@kdfid,'area-') and @kdfapp='mdmUI' and @kdfpage='myDeals' and contains(text(),'GSP')]/ancestor::tr/descendant::a[starts-with(@kdfid,'deal-link-')]";
	public static String value_399 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()!=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/preceding-sibling::td[starts-with(@kdfid,'theater_')]";
	public static String value_359 = "//*[starts-with(@kdfid,'approvalrequired-') and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_360 = "//*[@kdfid='comments' and @kdfapp='mdmUI' and @kdfpage='updateApprovalDecision']";
	public static String value_383 = "//*[@kdfid='theaterList' and @kdfapp='mdmUI' and @kdfpage='addProxy']";
	public static String value_384 = "//*[@kdfid='roleList' and @kdfapp='mdmUI' and @kdfpage='addProxy']";
	public static String value_385 = "//*[@kdfid='proxyName' and @kdfapp='mdmUI' and @kdfpage='addProxy']";
	public static String value_386 = "//*[@kdfid='proxyName' and @kdfapp='mdmUI' and @kdfpage='addProxy']/following-sibling::ul/li/a";
	public static String value_387 = "//*[@kdfid='savebtn' and @kdfapp='mdmUI' and @kdfpage='addProxy']";
	public static String value_420 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area Service Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JAMES SCOTT')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate_')]";
	public static String value_388 = "//*[@kdfid='addProxyErrorMessage' and @kdfapp='mdmUI' and @kdfpage='executiveSummary']";
	public static String value_421 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area Service Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JAMES SCOTT')]/following-sibling::td[starts-with(@kdfid,'proxyEndDate_')]";
	public static String value_389 = "//*[@kdfid='cancelbtn' and @kdfapp='mdmUI' and @kdfpage='addProxy']";
	public static String value_422 = "//*[starts-with(@kdfid,'dropdown-') and @kdfapp='mdmUI' and @kdfpage='ngmdmPage']";
	public static String value_423 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()!=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/preceding-sibling::td[starts-with(@kdfid,'theater_')]";
	public static String value_424 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()!=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_425 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/preceding-sibling::td[starts-with(@kdfid,'theater_')]";
	public static String value_426 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate') and text()=//following-sibling::td[starts-with(@kdfid,'proxyEndDate')]]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_427 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate_')]";
	public static String value_428 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyEndDate_')]";
	public static String value_429 = "//td[contains(text(),'MBANCHI')]/preceding-sibling::td/input[contains(@kdfid,'MBANCHI')]";
	public static String value_390 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]";
	public static String value_391 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'MICHAEL BANCHI')]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_392 = "//*[@kdfid='endDateCalendar' and @kdfapp='mdmUI' and @kdfpage='addProxy']";
	public static String value_393 = "//button[contains(@id,'datepicker') and contains(@id,'title')]";
	public static String value_372 = "//*[@kdfid='editDealAppRoute' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_373 = "//*[@kdfid='editDealOptyName' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_374 = "//*[@kdfid='editDealAccName' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_375 = "//*[@kdfid='editDealOptyOwner' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_376 = "//*[@kdfid='editDealSalesController' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_377 = "//*[@kdfid='editDealArea' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_410 = "//button[@class='btn btn-default btn-sm active']/span[text()='01']";
	public static String value_378 = "//*[@kdfid='editDealCountry' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_411 = "//*[starts-with(@kdfid,'theater_') and @kdfapp='mdmUI' and @kdfpage='existingProxy' and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyEndDate') and contains(text(),'01')]";
	public static String value_379 = "//*[@kdfid='editDealCance' and @kdfapp='mdmUI' and @kdfpage='editDeal']";
	public static String value_412 = "//*[starts-with(@kdfid,'theater_') and @kdfapp='mdmUI' and @kdfpage='existingProxy' and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate')]";
	public static String value_413 = "//*[starts-with(@kdfid,'theater_') and @kdfapp='mdmUI' and @kdfpage='existingProxy' and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Regional Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'ALI AMER')]/following-sibling::td[starts-with(@kdfid,'proxyEndDate')]";
	public static String value_414 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area VP')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JOHN HURLEY')]";
	public static String value_415 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area VP')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JOHN HURLEY')]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_416 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area VP')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JOHN HURLEY')]/following-sibling::td[starts-with(@kdfid,'proxyStartDate_')]";
	public static String value_417 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area VP')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JOHN HURLEY')]/following-sibling::td[starts-with(@kdfid,'proxyEndDate_')]";
	public static String value_418 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area Service Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JAMES SCOTT')]";
	public static String value_419 = "//*[starts-with(@kdfid,'theater_') and contains(text(),'GLOBAL SERVICE PROVIDER')]/following-sibling::td[starts-with(@kdfid,'userJobRole_') and contains(text(),'Area Service Manager')]/following-sibling::td[starts-with(@kdfid,'proxyName_') and contains(text(),'JAMES SCOTT')]/following-sibling::td[*]/a[starts-with(@kdfid,'editicon')]";
	public static String value_380 = "//input[@type='text']";
	public static String value_381 = "//*[@kdfid='addNewProxy' and @kdfapp='mdmUI' and @kdfpage='myDeals']";
	public static String value_382 = "//*[@kdfid='addproxy' and @kdfapp='mdmUI' and @kdfpage='existingProxy']";
}
